### Get all games

GET http://localhost:3000/v1/games HTTP/1.1

### Get specific game

GET http://localhost:3000/v1/games/the-salt-traverse HTTP/1.1

### Get choice by ID

GET http://localhost:3000/games/the-shattered-sun/choices/start HTTP/1.1
