AWSTemplateFormatVersion: 2010-09-09
Description: >-
  API for cyoa project

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - test
    Description: Environment for deploy

Mappings:
  EnvironmentMap:
    prod:
      certificate: adce1a21-90b4-4120-8548-111215e582f0
      corsDomain: https://cyoa.dbowland.com
      domain: cyoa-api.dbowland.com
      gamesTable: cyoa-api-games
      logStreamFunction: log-subscriber
      narrativesTable: cyoa-api-narratives
      project: cyoa
      promptsTable: cyoa-api-prompts
      scheduledGameCreationEnabled: true
      zoneId: Z072422417XWM8PIXXSFA
    test:
      certificate: 6a48cba7-feb9-4de5-8cbf-d383140fcdef
      corsDomain: https://cyoa.bowland.link
      domain: cyoa-api.bowland.link
      gamesTable: cyoa-api-games-test
      logStreamFunction: log-subscriber-test
      narrativesTable: cyoa-api-narratives-test
      project: cyoa-test
      promptsTable: cyoa-api-prompts-test
      scheduledGameCreationEnabled: false
      zoneId: Z01312547RGU1BYKIJXY

Resources:
  # API Gateway

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowCredentials: true
        AllowHeaders:
          - Authorization
          - Content-Type
          - X-Amz-Date
          - X-Amz-Security-Token
          - X-Api-Key
          - X-Twitch-Token
        AllowMethods:
          - GET
          - OPTIONS
        AllowOrigins:
          - !FindInMap [EnvironmentMap, !Ref Environment, corsDomain]
      Domain:
        BasePath:
          - /v1
        CertificateArn: !Sub
          - 'arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/${Certificate}'
          - Certificate: !FindInMap [EnvironmentMap, !Ref Environment, certificate]
        DomainName: !FindInMap [EnvironmentMap, !Ref Environment, domain]
        EndpointConfiguration: REGIONAL
        Route53:
          DistributionDomainName: !FindInMap [EnvironmentMap, !Ref Environment, domain]
          HostedZoneId: !FindInMap [EnvironmentMap, !Ref Environment, zoneId]
      FailOnWarnings: true
      StageName: v1
      Tags:
        'created-by': 'cyoa-api'
        'created-for': 'cyoa'
        'environment': !Ref Environment

  # Games

  GetGamesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-games.getGamesHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 1536
      Description: Retrieve available games
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          DEBUG_LOGGING: 'false'
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /games
            Method: get
      Tags:
        'created-by': 'cyoa-api'
        'created-for': 'cyoa'
        'environment': !Ref Environment
      Timeout: 15
      Tracing: Active
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2023'
        Sourcemap: true
        EntryPoints:
          - src/handlers/get-games.ts

  GetGamesLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${GetGamesFunction}
      RetentionInDays: 30
      Tags:
        - Key: 'created-by'
          Value: 'cyoa-api'
        - Key: 'created-for'
          Value: 'cyoa'
        - Key: 'environment'
          Value: !Ref Environment

  GetGamesGroupSubscription:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: !Sub
        - 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${Function}'
        - Function: !FindInMap [EnvironmentMap, !Ref Environment, logStreamFunction]
      FilterPattern: '[timestamp, uuid, level="ERROR", message]'
      LogGroupName: !Ref GetGamesLogGroup

  GetGameByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-game-by-id.getGameByIdHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 1024
      Description: Retrieve game by ID
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: !Ref GamesTable
      Environment:
        Variables:
          DEBUG_LOGGING: 'false'
          DYNAMODB_GAMES_TABLE_NAME: !Ref GamesTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /games/{gameId}
            Method: get
      Tags:
        'created-by': 'cyoa-api'
        'created-for': 'cyoa'
        'environment': !Ref Environment
      Timeout: 15
      Tracing: Active
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2023'
        Sourcemap: true
        EntryPoints:
          - src/handlers/get-game-by-id.ts

  GetGameByIdLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${GetGameByIdFunction}
      RetentionInDays: 30
      Tags:
        - Key: 'created-by'
          Value: 'cyoa-api'
        - Key: 'created-for'
          Value: 'cyoa'
        - Key: 'environment'
          Value: !Ref Environment

  GetGameByIdGroupSubscription:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: !Sub
        - 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${Function}'
        - Function: !FindInMap [EnvironmentMap, !Ref Environment, logStreamFunction]
      FilterPattern: '[timestamp, uuid, level="ERROR", message]'
      LogGroupName: !Ref GetGameByIdLogGroup

  # Scheduled Game Creation

  CreateGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/create-game.createGameHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 1536
      Description: Create new CYOA game
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref GamesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref NarrativesTable
        - DynamoDBReadPolicy:
            TableName: !Ref PromptsTable
        - Version: 2012-10-17
          Statement:
            - Action:
                - 'aws-marketplace:ViewSubscriptions'
                - 'aws-marketplace:Subscribe'
                - 'bedrock:InvokeModel*'
              Effect: Allow
              Resource: '*'
        - Version: 2012-10-17
          Statement:
            - Action:
                - 'lambda:InvokeFunction'
              Effect: Allow
              Resource: !GetAtt CreateNarrativeFunction.Arn
      Environment:
        Variables:
          CREATE_NARRATIVE_FUNCTION_NAME: !Ref CreateNarrativeFunction
          DEBUG_LOGGING: 'false'
          DYNAMODB_GAMES_TABLE_NAME: !Ref GamesTable
          DYNAMODB_NARRATIVES_TABLE_NAME: !Ref NarrativesTable
          DYNAMODB_PROMPTS_TABLE_NAME: !Ref PromptsTable
          INSPIRATION_ADJECTIVES_COUNT: 15
          INSPIRATION_NOUNS_COUNT: 25
          INSPIRATION_VERBS_COUNT: 20
          PROMPT_ID_CREATE_GAME: create-game
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: 'cron(5 4 2/3 * ? *)'
            Description: Create game every three days at 4-5am UTC
            Enabled: !FindInMap [EnvironmentMap, !Ref Environment, scheduledGameCreationEnabled]
      Tags:
        'created-by': 'cyoa-api'
        'created-for': 'cyoa'
        'environment': !Ref Environment
      Timeout: 295
      Tracing: Active
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2023'
        Sourcemap: true
        EntryPoints:
          - src/handlers/create-game.ts

  CreateGameLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${CreateGameFunction}
      RetentionInDays: 30
      Tags:
        - Key: 'created-by'
          Value: 'cyoa-api'
        - Key: 'created-for'
          Value: 'cyoa'
        - Key: 'environment'
          Value: !Ref Environment

  CreateGameGroupSubscription:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: !Sub
        - 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${Function}'
        - Function: !FindInMap [EnvironmentMap, !Ref Environment, logStreamFunction]
      FilterPattern: '[timestamp, uuid, level="ERROR", message]'
      LogGroupName: !Ref CreateGameLogGroup

  # Narratives

  GetNarrativeByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-narrative-by-id.getNarrativeByIdHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 1024
      Description: Retrieve narrative by ID
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: !Ref GamesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref NarrativesTable
        - Version: 2012-10-17
          Statement:
            - Action:
                - 'lambda:InvokeFunction'
              Effect: Allow
              Resource: !GetAtt CreateNarrativeFunction.Arn
      Environment:
        Variables:
          CREATE_NARRATIVE_FUNCTION_NAME: !Ref CreateNarrativeFunction
          DEBUG_LOGGING: 'false'
          DYNAMODB_GAMES_TABLE_NAME: !Ref GamesTable
          DYNAMODB_NARRATIVES_TABLE_NAME: !Ref NarrativesTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /games/{gameId}/narratives/{narrativeId}
            Method: get
      Tags:
        'created-by': 'cyoa-api'
        'created-for': 'cyoa'
        'environment': !Ref Environment
      Timeout: 15
      Tracing: Active
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2023'
        Sourcemap: true
        EntryPoints:
          - src/handlers/get-narrative-by-id.ts

  GetNarrativeByIdLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${GetNarrativeByIdFunction}
      RetentionInDays: 30
      Tags:
        - Key: 'created-by'
          Value: 'cyoa-api'
        - Key: 'created-for'
          Value: 'cyoa'
        - Key: 'environment'
          Value: !Ref Environment

  GetNarrativeByIdGroupSubscription:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: !Sub
        - 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${Function}'
        - Function: !FindInMap [EnvironmentMap, !Ref Environment, logStreamFunction]
      FilterPattern: '[timestamp, uuid, level="ERROR", message]'
      LogGroupName: !Ref GetNarrativeByIdLogGroup

  # CreateNarrativeFunction is only invoked by other lambdas
  CreateNarrativeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/create-narrative.createNarrativeHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 1536
      Description: Create CYOA narrative
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: !Ref GamesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref NarrativesTable
        - DynamoDBReadPolicy:
            TableName: !Ref PromptsTable
        - Version: 2012-10-17
          Statement:
            - Action:
                - 'aws-marketplace:ViewSubscriptions'
                - 'aws-marketplace:Subscribe'
                - 'bedrock:InvokeModel*'
              Effect: Allow
              Resource: '*'
      Environment:
        Variables:
          DEBUG_LOGGING: 'false'
          DYNAMODB_GAMES_TABLE_NAME: !Ref GamesTable
          DYNAMODB_NARRATIVES_TABLE_NAME: !Ref NarrativesTable
          DYNAMODB_PROMPTS_TABLE_NAME: !Ref PromptsTable
          INSPIRATION_ADJECTIVES_COUNT: 1
          INSPIRATION_NOUNS_COUNT: 3
          INSPIRATION_VERBS_COUNT: 2
          PROMPT_ID_CREATE_NARRATIVE: create-narrative
          PROMPT_ID_LOSE_GAME: lose-game
          PROMPT_ID_WIN_GAME: win-game
      Tags:
        'created-by': 'cyoa-api'
        'created-for': 'cyoa'
        'environment': !Ref Environment
      Timeout: 295
      Tracing: Active
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2023'
        Sourcemap: true
        EntryPoints:
          - src/handlers/create-narrative.ts

  CreateNarrativeLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${CreateNarrativeFunction}
      RetentionInDays: 30
      Tags:
        - Key: 'created-by'
          Value: 'cyoa-api'
        - Key: 'created-for'
          Value: 'cyoa'
        - Key: 'environment'
          Value: !Ref Environment

  CreateNarrativeGroupSubscription:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: !Sub
        - 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${Function}'
        - Function: !FindInMap [EnvironmentMap, !Ref Environment, logStreamFunction]
      FilterPattern: '[timestamp, uuid, level="ERROR", message]'
      LogGroupName: !Ref CreateNarrativeLogGroup

  # DynamoDB

  GamesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: GameId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: GameId
          KeyType: HASH
      TableName: !FindInMap [EnvironmentMap, !Ref Environment, gamesTable]
      Tags:
        - Key: 'created-by'
          Value: 'cyoa-api'
        - Key: 'created-for'
          Value: 'cyoa'
        - Key: 'environment'
          Value: !Ref Environment

  NarrativesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: GameId
          AttributeType: S
        - AttributeName: NarrativeId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: GameId
          KeyType: HASH
        - AttributeName: NarrativeId
          KeyType: RANGE
      TableName: !FindInMap [EnvironmentMap, !Ref Environment, narrativesTable]
      Tags:
        - Key: 'created-by'
          Value: 'cyoa-api'
        - Key: 'created-for'
          Value: 'cyoa'
        - Key: 'environment'
          Value: !Ref Environment

  PromptsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: PromptId
          AttributeType: S
        - AttributeName: UpdatedAt
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: PromptId
          KeyType: HASH
        - AttributeName: UpdatedAt
          KeyType: RANGE
      TableName: !FindInMap [EnvironmentMap, !Ref Environment, promptsTable]
      Tags:
        - Key: 'created-by'
          Value: 'cyoa-api'
        - Key: 'created-for'
          Value: 'cyoa'
        - Key: 'environment'
          Value: !Ref Environment
